version: 20.10.3.{build}
image: Visual Studio 2019

configuration:
  - Release

init:
  - ps: Update-AppveyorBuild -Version "$(Get-Date -format yy.MM).$env:appveyor_build_number"

environment:
    PRJ_NAME: 'fsu'
    TEST_ASSEMBLY: '%PRJ_NAME%.core.tests\bin\%CONFIGURATION%\%PRJ_NAME%.core.tests.dll'
    COVERALLS_REPO_TOKEN:
      secure: Hue3gKAzE3Le1CRWfY2ygW4/t4ZfOuQJG7Zibq1osm4/AA8WmTRgsUhtuSNyAXtf

skip_tags: true
skip_commits:
    files:
      - '**/*.md'

#cache:
#  - 'C:\ProgramData\chocolatey\bin -> appveyor.yml'
#  - 'C:\ProgramData\chocolatey\lib -> appveyor.yml'
#  - 'C:\Program Files (x86)\Inno Setup 6 -> appveyor.yml'


install:
  - dotnet tool install coveralls.net --global --version 1.0.0
#  - choco install gitversion.portable -pre -y --version 5.2.4
#  - choco install -y innosetup --version 6.0.4
#  - set PATH="C:\Program Files (x86)\Inno Setup 6";%PATH%

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore
 # - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: '%PRJ_NAME%.sln'
  verbosity: minimal

test_script:
  - cmd: >-
      
      %USERPROFILE%\.nuget\packages\opencover\4.7.922\tools\OpenCover.Console.exe -register:administrator -target:"%xunit20%\xunit.console.exe" -targetargs:"%TEST_ASSEMBLY% -appveyor -noshadow" -filter:"+[fsu*]* -[*.tests]* -[*.Tests]*" -output:".\coverage_%CONFIGURATION%.xml"
      
      %USERPROFILE%\.dotnet\tools\csmacnz.Coveralls.exe --opencover -i "./coverage_%CONFIGURATION%.xml" --serviceName AppVeyor --repoToken "%COVERALLS_REPO_TOKEN%"

artifacts:
- path: fsu\bin\Release\fsu.exe
  name: fsu